//═══════════════════════════════════════════════════════════════════════════════
// File: TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq.sv
// Auto-generated by UVM Generator
// Generated: 2026-01-19 22:57:59
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//═══════════════════════════════════════════════════════════════════════════════

class TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq extends uvm_sequence;

  `uvm_object_utils(TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq)
  `uvm_declare_p_sequencer(p18_dimc_tile_wrap_virtual_sequencer)

  // Sequences (ONLY for active UVCs)
  istream_directed_write_sequence#(64)      seq_feat_wr;
  dpmem_directed_write_sequence#(64,9)      seq_ker_wr;
  spmem_directed_write_sequence#(64,4)      seq_addin_wr;
  computation_configure_write_seq           seq_compu_wr;
  ostream_random_burst_read_sequence#(64)   seq_outbuf_rd;

  // Variables
  int mode, feature_buffer_size, sign_8b, PS_FIRST, PS_MODE, PS_LAST;

  function new(string name = "TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq");
    super.new(name);
  endfunction

  task body();

    string kernel_file;
    string feature_file;
    string psin_hex32_file;
    string addin_hex32_file;
    string output_file;

    int ret;

    // a. Set parameters
    mode                = 0;
    feature_buffer_size  = 1;
    sign_8b             = 0;
    PS_FIRST            = 1;
    PS_MODE             = 0;
    PS_LAST             = 0;

    kernel_file      = "./kernel_hex_rtl.txt";
    feature_file     = "./feature_hex_rtl.txt";
    psin_hex32_file   = "./psin_hex32_input.txt";
    addin_hex32_file  = "./addin_hex32_input.txt";
    output_file      = "./golden.txt";

    // b. Generate stimulus data using $system calls
    ret = $system($sformatf("python generate_data_hex_unique.py %0d %0d %0d", mode, feature_buffer_size, sign_8b));
    if (ret != 0) `uvm_fatal(get_type_name(), $sformatf("Data generation failed: generate_data_hex_unique.py ret=%0d", ret))

    // has_psin is False for this test; do not call generate_data_psin_addin.py

    ret = $system($sformatf("./psout_exe %s %s %s %s %s %0d %0d %0d %0d %0d",
                            kernel_file, feature_file, psin_hex32_file, addin_hex32_file, output_file,
                            mode, sign_8b, PS_FIRST, PS_MODE, PS_LAST));
    if (ret != 0) `uvm_fatal(get_type_name(), $sformatf("C reference model failed ret=%0d", ret))

    // c. Setup capture on vif
    p_sequencer.vif.capture_output_buffer_exp_data(output_file);

    // Create sequences
    seq_feat_wr   = istream_directed_write_sequence#(64)::type_id::create("seq_feat_wr");
    seq_ker_wr    = dpmem_directed_write_sequence#(64,9)::type_id::create("seq_ker_wr");
    seq_addin_wr  = spmem_directed_write_sequence#(64,4)::type_id::create("seq_addin_wr");
    seq_compu_wr  = computation_configure_write_seq::type_id::create("seq_compu_wr");
    seq_outbuf_rd = ostream_random_burst_read_sequence#(64)::type_id::create("seq_outbuf_rd");

    // d. Initialize computation (START_COMPUTE=0, COMPE=0)
    seq_compu_wr.START_COMPUTE = 0;
    seq_compu_wr.COMPE         = 0;
    seq_compu_wr.mode          = mode;
    seq_compu_wr.sign_8b       = sign_8b;
    seq_compu_wr.PS_FIRST      = PS_FIRST;
    seq_compu_wr.PS_MODE       = PS_MODE;
    seq_compu_wr.PS_LAST       = PS_LAST;
    seq_compu_wr.start(p_sequencer.seqr_compu);

    // e. Write input data sequences (ONLY for active UVCs)
    seq_feat_wr.size      = 16;
    seq_feat_wr.file_path = feature_file;
    seq_feat_wr.start(p_sequencer.seqr_feature_buffer);

    seq_ker_wr.size      = 512;
    seq_ker_wr.file_path = kernel_file;
    seq_ker_wr.start(p_sequencer.seqr_kernel_mem);

    seq_addin_wr.size      = 16;
    seq_addin_wr.file_path = "./addin_hex_rtl.txt";
    seq_addin_wr.start(p_sequencer.seqr_addin);

    // f. Start computation (START_COMPUTE=1, COMPE=1)
    seq_compu_wr.START_COMPUTE = 1;
    seq_compu_wr.COMPE         = 1;
    seq_compu_wr.mode          = mode;
    seq_compu_wr.sign_8b       = sign_8b;
    seq_compu_wr.PS_FIRST      = PS_FIRST;
    seq_compu_wr.PS_MODE       = PS_MODE;
    seq_compu_wr.PS_LAST       = PS_LAST;
    seq_compu_wr.start(p_sequencer.seqr_compu);

    // g. Wait for psout_buff_full == 1
    @(posedge p_sequencer.vif.psout_buff_full);

    // h. Read output buffer: size=32, start on seqr_output_buffer
    seq_outbuf_rd.size = 32;
    seq_outbuf_rd.start(p_sequencer.seqr_output_buffer);

    // i. Cleanup: $system calls to remove/rename temp files
    void'($system("rm -f ./psin_hex_rtl.txt"));
    void'($system("rm -f ./psin_hex32_input.txt"));
    void'($system("rm -f ./addin_hex32_input.txt"));

  endtask

endclass