//═══════════════════════════════════════════════════════════════════════════════
// File: TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq.sv
// Auto-generated by UVM Generator
// Generated: 2026-01-19 21:29:06
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//═══════════════════════════════════════════════════════════════════════════════

//-----------------------------------------------------------------------------
// Title      : TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq
// File       : TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq.sv
//-----------------------------------------------------------------------------

class TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq extends uvm_sequence;

  `uvm_object_utils(TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq)
  `uvm_declare_p_sequencer(p18_dimc_tile_wrap_virtual_sequencer)

  // Sequence declarations for active UVCs
  istream_directed_write_sequence#(64)              seq_feat_wr;
  dpmem_directed_write_sequence#(64,9)              seq_ker_wr;
  spmem_directed_write_sequence#(64,4)              seq_addin_wr;
  computation_configure_write_seq                   seq_compu_wr;
  ostream_random_burst_read_sequence#(64)           seq_outbuf_rd;

  // Parameter variables
  int mode;
  int feature_buffer_size;
  int sign_8b;
  int PS_FIRST;
  int PS_MODE;
  int PS_LAST;

  function new(string name = "TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq");
    super.new(name);
  endfunction

  virtual task body();
    super.body();

    // a. Set parameters
    mode                = 0;
    feature_buffer_size = 1;
    sign_8b             = 0;
    PS_FIRST            = 1;
    PS_MODE             = 0;
    PS_LAST             = 0;

    // b. Generate stimulus data via system calls
    $display("%t : [TC] Generating stimulus: python generate_data_hex_unique.py %0d %0d %0d", $time, mode, feature_buffer_size, sign_8b);
    void'($system($sformatf("python generate_data_hex_unique.py %0d %0d %0d", mode, feature_buffer_size, sign_8b)));
    $display("%t : [TC] Generating ADDIN+PSIN data: python generate_data_psin_addin.py", $time);
    void'($system("python generate_data_psin_addin.py"));
    $display("%t : [TC] Running C model: ./psout_exe %0d %0d %0d %0d %0d %0d", $time, mode, feature_buffer_size, sign_8b, PS_FIRST, PS_MODE, PS_LAST);
    void'($system($sformatf("./psout_exe %0d %0d %0d %0d %0d %0d", mode, feature_buffer_size, sign_8b, PS_FIRST, PS_MODE, PS_LAST)));

    // c. Setup capture signals
    p_sequencer.vif.setup_capture();

    // d. Initialize computation
    p_sequencer.vif.set_start_compute(0);
    p_sequencer.vif.set_compe(0);

    // e. Write input data sequences (ONLY active UVCs)
    // Feature buffer
    seq_feat_wr = istream_directed_write_sequence#(64)::type_id::create("seq_feat_wr");
    seq_feat_wr.data_file = "./feature_hex_rtl.txt";
    seq_feat_wr.size      = 16;
    seq_feat_wr.start(p_sequencer.m_feature_buffer_env.sequencer);

    // Kernel memory
    seq_ker_wr = dpmem_directed_write_sequence#(64,9)::type_id::create("seq_ker_wr");
    seq_ker_wr.data_file  = "./kernel_hex_rtl.txt";
    seq_ker_wr.size       = 512;
    seq_ker_wr.start(p_sequencer.m_kernel_mem_env.sequencer);

    // ADDIN
    seq_addin_wr = spmem_directed_write_sequence#(64,4)::type_id::create("seq_addin_wr");
    seq_addin_wr.data_file = "./addin_hex_rtl.txt";
    seq_addin_wr.size      = 16;
    seq_addin_wr.start(p_sequencer.m_addin_env.sequencer);

    // Configure computation
    seq_compu_wr = computation_configure_write_seq::type_id::create("seq_compu_wr");
    seq_compu_wr.mode      = mode;
    seq_compu_wr.sign_8b   = sign_8b;
    seq_compu_wr.PS_FIRST  = PS_FIRST;
    seq_compu_wr.PS_MODE   = PS_MODE;
    seq_compu_wr.PS_LAST   = PS_LAST;
    seq_compu_wr.start(p_sequencer.m_computation_env.sequencer);

    // f. Start computation
    p_sequencer.vif.set_start_compute(1);
    p_sequencer.vif.set_compe(1);

    // g. Wait for psout_buff_full == 1
    wait (p_sequencer.vif.psout_buff_full == 1);

    // h. Read output buffer
    seq_outbuf_rd = ostream_random_burst_read_sequence#(64)::type_id::create("seq_outbuf_rd");
    seq_outbuf_rd.size = 32;
    seq_outbuf_rd.start(p_sequencer.m_output_buffer_env.sequencer);

    // i. Cleanup temp files
    $display("%t : [TC] Cleaning up temp files...", $time);
    void'($system("rm -f feature_hex_rtl.txt kernel_hex_rtl.txt addin_hex_rtl.txt psin_hex_rtl.txt psout_hex_rtl.txt"));
    void'($system("mv -f psout_hex_c.txt psout_hex_gld.txt"));

  endtask : body

endclass : TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq