//═══════════════════════════════════════════════════════════════════════════════
// File: dimc_tile_wrap_pkg.sv
// Auto-generated by UVM Generator
// Generated: 2026-01-19 22:58:02
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//═══════════════════════════════════════════════════════════════════════════════

// DIMC TILE WRAP package file importing all files 
package dimc_tile_wrap_pkg;
	import uvm_pkg::*;
        import istream_pkg::*;
        import dpmem_pkg::*;
        //import psin_pkg::*;
        import spmem_pkg::*;
        import computation_pkg::*;
        import ostream_pkg::*;
        `include "uvm_macros.svh"
        //`include "dimc_tile_wrap_if_interface.sv""

         `include "p18_dimc_tile_wrap_virtual_sequencer.sv"
         `include "p18_dimc_tile_wrap_scoreboard.sv"
         `include "p18_dimc_tile_wrap_env.sv"
		   // add here the virtual sequences
	 `include "TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq.sv"

		   // add here the test files
	 `include "TC_S2_SF_MODE00_PS_FIRST_K0F0_test.sv"

endpackage