"""
File management utilities for UVM Generator
"""

import os
import shutil
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime


class FileManager:
    """Manages file operations for generated UVM files"""
    
    def __init__(self, output_base: str):
        self.output_base = Path(output_base)
        self.created_files: List[Path] = []
    
    def setup_directories(self):
        """Create output directory structure"""
        dirs = [
            self.output_base / "ip_infra" / "env",
            self.output_base / "ip_infra" / "interface",
            self.output_base / "ip_infra" / "virtual_sequencer",
            self.output_base / "ip_infra" / "pkg",
            self.output_base / "ip_infra" / "tb",
            self.output_base / "ip_infra" / "scoreboard",
            self.output_base / "tests" / "tests",
            self.output_base / "tests" / "virtual_sequences",
        ]
        
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)
        
        return dirs
    
    def write_file(self, relative_path: str, content: str, add_header: bool = True) -> Path:
        """Write content to file with optional auto-generated header"""
        file_path = self.output_base / relative_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        
        if add_header:
            header = self._generate_header(file_path.name)
            content = header + content
        
        # Use UTF-8 encoding for Windows compatibility
        file_path.write_text(content, encoding='utf-8')
        self.created_files.append(file_path)
        
        return file_path
    
    def _generate_header(self, filename: str) -> str:
        """Generate auto-generated file header"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return f"""//═══════════════════════════════════════════════════════════════════════════════
// File: {filename}
// Auto-generated by UVM Generator
// Generated: {timestamp}
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//═══════════════════════════════════════════════════════════════════════════════

"""
    
    def copy_file(self, source: str, dest_relative: str) -> Path:
        """Copy a file to the output directory"""
        dest_path = self.output_base / dest_relative
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, dest_path)
        self.created_files.append(dest_path)
        return dest_path
    
    def read_example_file(self, file_path: str) -> str:
        """Read an example file for few-shot learning"""
        path = Path(file_path)
        if path.exists():
            return path.read_text(encoding='utf-8')
        return ""
    
    def get_created_files(self) -> List[Path]:
        """Return list of all created files"""
        return self.created_files
    
    def generate_summary(self) -> str:
        """Generate summary of created files"""
        summary = ["=" * 60]
        summary.append("Generated Files Summary")
        summary.append("=" * 60)
        
        # Group by directory
        by_dir: Dict[str, List[str]] = {}
        for f in self.created_files:
            dir_name = str(f.parent.relative_to(self.output_base))
            if dir_name not in by_dir:
                by_dir[dir_name] = []
            by_dir[dir_name].append(f.name)
        
        for dir_name, files in sorted(by_dir.items()):
            summary.append(f"\n{dir_name}/")
            for f in sorted(files):
                summary.append(f"  └── {f}")
        
        summary.append(f"\nTotal files generated: {len(self.created_files)}")
        summary.append("=" * 60)
        
        return "\n".join(summary)


def collect_uvc_info(uvc_lib_path: str) -> Dict[str, str]:
    """Collect information about available UVCs"""
    uvc_info = {}
    uvc_path = Path(uvc_lib_path)
    
    if not uvc_path.exists():
        return uvc_info
    
    for uvc_dir in uvc_path.iterdir():
        if uvc_dir.is_dir():
            uvc_name = uvc_dir.name
            
            # Collect sequence files
            seq_dir = uvc_dir / "sequences"
            if seq_dir.exists():
                sequences = []
                for seq_file in seq_dir.glob("*.sv"):
                    try:
                        content = seq_file.read_text(encoding='utf-8')
                    except UnicodeDecodeError:
                        content = seq_file.read_text(encoding='latin-1')
                    # Extract class declaration
                    import re
                    match = re.search(r'class\s+(\w+).*?extends', content, re.DOTALL)
                    if match:
                        sequences.append(match.group(0)[:200])
                
                uvc_info[uvc_name] = "\n".join(sequences)
    
    return uvc_info


def collect_example_files(example_dir: str) -> Dict[str, str]:
    """Collect example files for few-shot learning"""
    examples = {}
    example_path = Path(example_dir)
    
    # Define expected example file patterns
    patterns = {
        'env': ['*env*.sv', '*_env.sv'],
        'vseqr': ['*virtual_sequencer*.sv', '*vseqr*.sv'],
        'interface': ['*interface*.sv', '*_if*.sv'],
        'package': ['*package*.sv', '*_pkg*.sv'],
        'test': ['*_test.sv'],
        'vseq': ['*_vseq.sv'],
    }
    
    for key, pats in patterns.items():
        for pat in pats:
            for f in example_path.rglob(pat):
                if f.is_file():
                    try:
                        examples[key] = f.read_text(encoding='utf-8')
                    except UnicodeDecodeError:
                        examples[key] = f.read_text(encoding='latin-1')
                    break
            if key in examples:
                break
    
    return examples
