//==============================================================================
// File: dimc_tile_if.sv
// Auto-generated by UVM Generator V2
// Generated: 2026-01-20 00:08:36
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//==============================================================================

interface dimc_tile_if (
  input  logic clk,
  input  logic resetn
);

  // --------------------------------------------------------------------------
  // Global control/status
  // --------------------------------------------------------------------------
  logic        soft_resetn;
  logic        enable;
  logic        start;
  logic        stop;

  logic        busy;
  logic        done;
  logic        error;
  logic [31:0] error_code;

  // Optional test/scan hooks
  logic        test_mode;
  logic        scan_enable;
  logic        scan_in;
  logic        scan_out;

  // --------------------------------------------------------------------------
  // m_computation_env (regbank_env) - mapped to model args: mode, sign_8b
  // --------------------------------------------------------------------------
  logic [31:0] mode;
  logic        sign_8b;

  // --------------------------------------------------------------------------
  // m_feature_buffer_env (istream_env#(64)) - mapped to model arg: feature
  // --------------------------------------------------------------------------
  logic        feature_valid;
  logic        feature_ready;
  logic [63:0] feature_data;
  logic [7:0]  feature_keep;
  logic        feature_last;

  logic        feature_buffer_full;
  logic        feature_buffer_empty;

  // --------------------------------------------------------------------------
  // m_psin_env (istream_env#(32)) - mapped to model arg: psin
  // --------------------------------------------------------------------------
  logic        psin_valid;
  logic        psin_ready;
  logic [31:0] psin_data;
  logic [3:0]  psin_keep;
  logic        psin_last;

  logic        psin_full;
  logic        psin_empty;

  // --------------------------------------------------------------------------
  // m_output_buffer_env (ostream_env#(64)) - mapped to model arg: psout
  // --------------------------------------------------------------------------
  logic        psout_valid;
  logic        psout_ready;
  logic [63:0] psout_data;
  logic [7:0]  psout_keep;
  logic        psout_last;

  logic        output_buffer_full;
  logic        output_buffer_empty;

  // --------------------------------------------------------------------------
  // m_kernel_mem_env (dpmem_env#(64,9)) - mapped to model arg: kernels
  // Dual-port memory style signals
  // --------------------------------------------------------------------------
  logic        kernels_a_cs;
  logic        kernels_a_we;
  logic [8:0]  kernels_a_addr;
  logic [63:0] kernels_a_wdata;
  logic [63:0] kernels_a_rdata;
  logic [7:0]  kernels_a_wstrb;

  logic        kernels_b_cs;
  logic        kernels_b_we;
  logic [8:0]  kernels_b_addr;
  logic [63:0] kernels_b_wdata;
  logic [63:0] kernels_b_rdata;
  logic [7:0]  kernels_b_wstrb;

  // --------------------------------------------------------------------------
  // m_addin_env (spmem_env#(64,4)) - mapped to model arg: addin
  // Single-port memory style signals
  // --------------------------------------------------------------------------
  logic        addin_cs;
  logic        addin_we;
  logic [3:0]  addin_addr;
  logic [63:0] addin_wdata;
  logic [63:0] addin_rdata;
  logic [7:0]  addin_wstrb;

  // --------------------------------------------------------------------------
  // Clocking block
  // --------------------------------------------------------------------------
  clocking cb @(posedge clk);
    // global control/status
    default input #1step output #1step;
    output soft_resetn;
    output enable;
    output start;
    output stop;

    input  busy;
    input  done;
    input  error;
    input  error_code;

    output test_mode;
    output scan_enable;
    output scan_in;
    input  scan_out;

    // regbank
    output mode;
    output sign_8b;

    // feature stream in
    output feature_valid;
    output feature_data;
    output feature_keep;
    output feature_last;
    input  feature_ready;
    input  feature_buffer_full;
    input  feature_buffer_empty;

    // psin stream in
    output psin_valid;
    output psin_data;
    output psin_keep;
    output psin_last;
    input  psin_ready;
    input  psin_full;
    input  psin_empty;

    // psout stream out
    input  psout_valid;
    input  psout_data;
    input  psout_keep;
    input  psout_last;
    output psout_ready;
    input  output_buffer_full;
    input  output_buffer_empty;

    // kernels dpmem
    output kernels_a_cs;
    output kernels_a_we;
    output kernels_a_addr;
    output kernels_a_wdata;
    output kernels_a_wstrb;
    input  kernels_a_rdata;

    output kernels_b_cs;
    output kernels_b_we;
    output kernels_b_addr;
    output kernels_b_wdata;
    output kernels_b_wstrb;
    input  kernels_b_rdata;

    // addin spmem
    output addin_cs;
    output addin_we;
    output addin_addr;
    output addin_wdata;
    output addin_wstrb;
    input  addin_rdata;
  endclocking

  // --------------------------------------------------------------------------
  // Default values
  // --------------------------------------------------------------------------
  initial begin
    soft_resetn          = 1'b1;
    enable               = 1'b0;
    start                = 1'b0;
    stop                 = 1'b0;

    test_mode            = 1'b0;
    scan_enable          = 1'b0;
    scan_in              = 1'b0;

    mode                 = '0;
    sign_8b              = 1'b0;

    feature_valid        = 1'b0;
    feature_data         = '0;
    feature_keep         = '0;
    feature_last         = 1'b0;

    psin_valid           = 1'b0;
    psin_data            = '0;
    psin_keep            = '0;
    psin_last            = 1'b0;

    psout_ready          = 1'b1;

    kernels_a_cs         = 1'b0;
    kernels_a_we         = 1'b0;
    kernels_a_addr       = '0;
    kernels_a_wdata      = '0;
    kernels_a_wstrb      = '0;

    kernels_b_cs         = 1'b0;
    kernels_b_we         = 1'b0;
    kernels_b_addr       = '0;
    kernels_b_wdata      = '0;
    kernels_b_wstrb      = '0;

    addin_cs             = 1'b0;
    addin_we             = 1'b0;
    addin_addr           = '0;
    addin_wdata          = '0;
    addin_wstrb          = '0;
  end

  // --------------------------------------------------------------------------
  // Helper tasks
  // --------------------------------------------------------------------------
  task automatic wait_for_completion(input int unsigned timeout_cycles = 0);
    int unsigned cycles;
    cycles = 0;

    // Wait for reset deassertion and enable/start sequencing is responsibility of TB;
    // This task just watches for done/error.
    while (1) begin
      @(posedge clk);
      if (!resetn || !soft_resetn) begin
        cycles = 0;
        continue;
      end
      if (done || error) break;
      if (timeout_cycles != 0) begin
        cycles++;
        if (cycles >= timeout_cycles) break;
      end
    end
  endtask

  task automatic capture_output_data(input string file_path);
    int fd;
    fd = $fopen(file_path, "w");
    if (fd == 0) return;

    while (1) begin
      @(posedge clk);
      if (!resetn || !soft_resetn) continue;

      if (psout_valid && psout_ready) begin
        $fwrite(fd, "%0t %016h %02h %0d\n", $time, psout_data, psout_keep, psout_last);
        if (psout_last) begin
          $fflush(fd);
        end
      end

      if (done || error) begin
        $fflush(fd);
        $fclose(fd);
        break;
      end
    end
  endtask

  // --------------------------------------------------------------------------
  // Modports
  // --------------------------------------------------------------------------
  modport dut (
    input  clk,
    input  resetn,

    input  soft_resetn,
    input  enable,
    input  start,
    input  stop,

    output busy,
    output done,
    output error,
    output error_code,

    input  test_mode,
    input  scan_enable,
    input  scan_in,
    output scan_out,

    input  mode,
    input  sign_8b,

    // feature stream
    input  feature_valid,
    input  feature_data,
    input  feature_keep,
    input  feature_last,
    output feature_ready,
    output feature_buffer_full,
    output feature_buffer_empty,

    // psin stream
    input  psin_valid,
    input  psin_data,
    input  psin_keep,
    input  psin_last,
    output psin_ready,
    output psin_full,
    output psin_empty,

    // psout stream
    output psout_valid,
    output psout_data,
    output psout_keep,
    output psout_last,
    input  psout_ready,
    output output_buffer_full,
    output output_buffer_empty,

    // kernels dpmem
    input  kernels_a_cs,
    input  kernels_a_we,
    input  kernels_a_addr,
    input  kernels_a_wdata,
    input  kernels_a_wstrb,
    output kernels_a_rdata,

    input  kernels_b_cs,
    input  kernels_b_we,
    input  kernels_b_addr,
    input  kernels_b_wdata,
    input  kernels_b_wstrb,
    output kernels_b_rdata,

    // addin spmem
    input  addin_cs,
    input  addin_we,
    input  addin_addr,
    input  addin_wdata,
    input  addin_wstrb,
    output addin_rdata
  );

  modport tb (
    input  clk,
    input  resetn,
    clocking cb,

    input  busy,
    input  done,
    input  error,
    input  error_code,

    input  feature_ready,
    input  feature_buffer_full,
    input  feature_buffer_empty,

    input  psin_ready,
    input  psin_full,
    input  psin_empty,

    input  psout_valid,
    input  psout_data,
    input  psout_keep,
    input  psout_last,
    input  output_buffer_full,
    input  output_buffer_empty,

    input  kernels_a_rdata,
    input  kernels_b_rdata,
    input  addin_rdata,

    input  scan_out
  );

endinterface