//==============================================================================
// File: TC_S2_SF_MODE00_PS_FIRST_K0F0_test.sv
// Auto-generated by UVM Generator V2
// Generated: 2026-01-20 00:09:21
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//==============================================================================

class TC_S2_SF_MODE00_PS_FIRST_K0F0_test extends uvm_test;
  `uvm_component_utils(TC_S2_SF_MODE00_PS_FIRST_K0F0_test)

  dimc_tile_env env;
  TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq vseq_compu;
  virtual dimc_tile_if vif;

  function new(string name = "TC_S2_SF_MODE00_PS_FIRST_K0F0_test", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    env = dimc_tile_env::type_id::create("env", this);
    vseq_compu = TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq::type_id::create("vseq_compu");

    if (!uvm_config_db#(virtual dimc_tile_if)::get(this, "", "vif", vif)) begin
      `uvm_fatal(get_type_name(), "Failed to get virtual interface 'vif' from uvm_config_db")
    end
  endfunction

  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
  endfunction

  task run_phase(uvm_phase phase);
    phase.raise_objection(this);

    wait (vif.resetn == 1);
    repeat (5) @(vif.cb);

    vseq_compu.start(env.v_seqr);

    repeat (10) @(vif.cb);
    phase.drop_objection(this);
  endtask

endclass