//═══════════════════════════════════════════════════════════════════════════════
// File: TC_S2_SF_MODE00_PS_FIRST_K0F0_test.sv
// Auto-generated by UVM Generator
// Generated: 2026-01-19 21:28:39
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//═══════════════════════════════════════════════════════════════════════════════

//------------------------------------------------------------------------------
// TC_S2_SF_MODE00_PS_FIRST_K0F0_test.sv
//------------------------------------------------------------------------------

class TC_S2_SF_MODE00_PS_FIRST_K0F0_test extends uvm_test;

   `uvm_component_utils(TC_S2_SF_MODE00_PS_FIRST_K0F0_test)

   p18_dimc_tile_wrap_env         env;
   TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq vseq_compu;
   virtual dimc_tilewrap_if       vif;

   function new(string name = "TC_S2_SF_MODE00_PS_FIRST_K0F0_test", uvm_component parent = null);
      super.new(name, parent);
   endfunction

   function void build_phase(uvm_phase phase);
      super.build_phase(phase);

      env = p18_dimc_tile_wrap_env::type_id::create("env", this);

      vseq_compu = TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq::type_id::create(
         $sformatf("vseq_compu_mode%02d_sign_%s", 0, "dont_care"), this);

      if (!uvm_config_db#(virtual dimc_tilewrap_if)::get(this, "", "dimc_tilewrap_vif", vif)) begin
         `uvm_fatal("NOVIF", "virtual interface dimc_tilewrap_vif not set in config_db")
      end
   endfunction

   function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);
   endfunction

   task run_phase(uvm_phase phase);
      phase.raise_objection(this);

      wait (vif.resetn == 1);
      repeat(5) @(vif.cb);

      vseq_compu.start(env.v_seqr);

      repeat(10) @(vif.cb);

      phase.drop_objection(this);
   endtask

endclass