//═══════════════════════════════════════════════════════════════════════════════
// File: TC_S2_SF_MODE00_PS_FIRST_K0F0_test.sv
// Auto-generated by UVM Generator
// Generated: 2026-01-19 22:57:42
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//═══════════════════════════════════════════════════════════════════════════════

class TC_S2_SF_MODE00_PS_FIRST_K0F0_test extends uvm_test;
  `uvm_component_utils(TC_S2_SF_MODE00_PS_FIRST_K0F0_test)

  p18_dimc_tile_wrap_env             env;
  TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq  vseq_compu;
  virtual dimc_tilewrap_if           vif;

  function new(string name = "TC_S2_SF_MODE00_PS_FIRST_K0F0_test", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    string vseq_name;

    super.build_phase(phase);

    env = p18_dimc_tile_wrap_env::type_id::create("env", this);

    vseq_name = $sformatf("vseq_compu_mode%0d_sign_%0s", 0, "dont_care");
    vseq_compu = TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq::type_id::create(vseq_name, this);

    if (!uvm_config_db#(virtual dimc_tilewrap_if)::get(this, "", "dimc_tilewrap_vif", vif)) begin
      `uvm_fatal(get_type_name(), "Failed to get virtual interface 'dimc_tilewrap_vif' from uvm_config_db")
    end
  endfunction

  virtual function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
  endfunction

  virtual task run_phase(uvm_phase phase);
    phase.raise_objection(this);

    wait (vif.resetn == 1'b1);
    repeat (5) @(vif.cb);

    vseq_compu.start(env.v_seqr);

    repeat (10) @(vif.cb);
    phase.drop_objection(this);
  endtask

endclass