//==============================================================================
// File: dimc_tile_pkg.sv
// Auto-generated by UVM Generator V2
// Generated: 2026-01-20 00:09:53
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//==============================================================================

package dimc_tile_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  import istream_pkg::*;
  import ostream_pkg::*;
  import dpmem_pkg::*;
  import spmem_pkg::*;
  import computation_pkg::*;

  // Infrastructure (order matters)
  `include "dimc_tile_virtual_sequencer.sv"
  `include "dimc_tile_scoreboard.sv"
  `include "dimc_tile_env.sv"

  // Virtual sequences
  `include "TC_S2_SF_MODE00_PS_FIRST_K0F0_vseq.sv"

  // Tests
  `include "TC_S2_SF_MODE00_PS_FIRST_K0F0_test.sv"

endpackage : dimc_tile_pkg