//==============================================================================
// File: dimc_tile_virtual_sequencer.sv
// Auto-generated by UVM Generator V2
// Generated: 2026-01-20 00:08:07
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//==============================================================================

class dimc_tile_virtual_sequencer extends uvm_sequencer;

  `uvm_component_utils(dimc_tile_virtual_sequencer)

  // Sub-sequencer pointers (to be connected in env connect_phase)
  istream_sequencer#(64) seqr_feature_buffer;
  istream_sequencer#(32) seqr_psin;
  dpmem_sequencer#(64,9) seqr_kernel_mem;
  spmem_sequencer#(64,4) seqr_addin;
  computation_sequencer  seqr_compu;
  ostream_sequencer#(64) seqr_output_buffer;

  // Virtual interface
  virtual dimc_tile_if vif;

  function new(string name = "dimc_tile_virtual_sequencer", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    if (!uvm_config_db#(virtual dimc_tile_if)::get(this, "", "dimc_tile_vif", vif))
      `uvm_fatal("NOVIF", "Virtual interface must be set for dimc_tile_if via config_db key 'dimc_tile_vif'")
  endfunction

endclass