//═══════════════════════════════════════════════════════════════════════════════
// File: dimc_tilewrap_if.sv
// Auto-generated by UVM Generator
// Generated: 2026-01-19 21:28:30
// 
// WARNING: This file is auto-generated. Manual changes may be overwritten.
//═══════════════════════════════════════════════════════════════════════════════

// dimc_tilewrap_if interface
// Auto-generated per requirements

interface dimc_tilewrap_if(input logic dimc_tilewrap_clk, input logic resetn);

  // Control signals (inputs to DUT)
  logic        SOFT_RESET;
  logic        DISABLE_STALL;
  logic        DISABLE_PS_STALL;
  logic        DISABLE_SOUT_STALL;
  logic        DISABLE_PSOUT_STALL;
  logic        CG_DISABLE;
  logic        feat_en;
  logic        tile_en;
  logic [7:0]  valid_feat_count;
  logic        psout_mode;
  logic        compute_mask;
  logic        test_si;
  logic        tst_scanmode;
  logic        tst_scanenable;
  logic        test_clk;

  // Helper signals
  logic        capture_output_buffer_exp_data;
  logic [31:0] output_buffer_exp_data_size;

  // Status signals (outputs from DUT)
  logic        test_so;
  logic        feat_buff_full;
  logic        feat_buff_empty;
  logic        psin_buff_full;
  logic        psin_buff_empty;
  logic        sout_buff_full;
  logic        sout_buff_empty;
  logic        psout_buff_full;
  logic        psout_buff_empty;

  // Clocking block for synchronous access
  clocking cb @(posedge dimc_tilewrap_clk);
    output SOFT_RESET, DISABLE_STALL, DISABLE_PS_STALL, DISABLE_SOUT_STALL, DISABLE_PSOUT_STALL;
    output CG_DISABLE, feat_en, tile_en, valid_feat_count, psout_mode, compute_mask;
    output test_si, tst_scanmode, tst_scanenable, test_clk;
    output capture_output_buffer_exp_data, output_buffer_exp_data_size;
    input  test_so, feat_buff_full, feat_buff_empty, psin_buff_full, psin_buff_empty;
    input  sout_buff_full, sout_buff_empty, psout_buff_full, psout_buff_empty;
  endclocking

  // Initial values for inputs
  initial begin
    SOFT_RESET                 = 1'b0;
    DISABLE_STALL              = 1'b0;
    DISABLE_PS_STALL           = 1'b0;
    DISABLE_SOUT_STALL         = 1'b0;
    DISABLE_PSOUT_STALL        = 1'b0;
    CG_DISABLE                 = 1'b0;
    feat_en                    = 1'b0;
    tile_en                    = 1'b0;
    valid_feat_count           = '0;
    psout_mode                 = 1'b0;
    compute_mask               = 1'b0;
    test_si                    = 1'b0;
    tst_scanmode               = 1'b0;
    tst_scanenable             = 1'b0;
    test_clk                   = 1'b0;
    capture_output_buffer_exp_data = 1'b0;
    output_buffer_exp_data_size = 32'b0;
  end

endinterface